[tool.autoflake]
check = false
in-place = true
recursive = true
imports = [
    "django",
    "https",
    "urllib3",
    "ujson",
    "djangorestframework",
    "pydash",
    "google",
    "jinja2",
    "httpx",
    "requests",
    "jsonschema",
    "psutil",
    "channels",
    "colour",
]

[tool.isort]
multi_line_output = 3
line_length = 120
include_trailing_comma = true
force_alphabetical_sort_within_sections = true
overwrite_in_place = true
combine_star = true
star_first = true
verbose = true

# [tool.black]
# line-length = 120

[tool.pylint.main]
recursive = true
ignore = ["manage.py"]
ignore-patterns = [".*urls.py.*", ".*migrations.*", ".*_pb2.*", "\\d{4}_.*?.py", "^gunicorn.*", "fixtures.py", "conftest.py", ".*_tests.py"]
extension-pkg-allow-list = ["httpx", "ujson"]
fail-under = 9.5
fail-on = [
    # all fatal-errors
    "F",
    #all errors
    "E",
    "C0209", # consider-using-f-string
    "R0205", # useless-object-inheritance
    "R0401", # cyclic-import
    "R1725", # super-with-arguments
    "R1734", # use-list-literal
    "R1735", # use-dict-literal
    "W0102", # dangerous-default-value
    "W0133", # pointless-exception-statement
    "W0223", # abstract-method
    "W0401", # wildcard-import
    "W0611", # unused-import
    "W0612", # unused-variable
    "W0622", # redefined-builtin
    "W0707", # raise-missing-from
    "W0718", # broad-exception-caught
    "W0719", # broad-exception-raised
    "W1113", # keyword-arg-before-vararg
    "W1114", # arguments-out-of-order
    "W1203", # logging-fstring-interpolation
    "W1309", # f-string-without-interpolation
    "W1510", # subprocess-run-check
]
enable = [
    "bad-inline-option",
    "useless-suppression",
    "deprecated-pragma"
]
disable = [
    'F0002', # astroid-error, pylint issues not ours
    # docstings
    'C0114',
    'C0115',
    'C0116',
    'C0411', # import order
    'C0415', # non top-level-imports
    'W0221', # arguments-differ between a class and its parent
    # 'E1101', # no-member → need a solution see https://github.com/pylint-dev/pylint/issues/1162
    'E0611' # no-name-in-module
]

[tool.pylint.format]
max-line-length = "120"
good-names = ["id", "pk", "_", "doRollover", "shouldRollover", "registry"]

[tool.pylint.design]
max-args = 8
max-attributes = 12
max-bool-expr = 5
max-public-methods = 30
max-returns = 12
min-public-methods = 0
max-parents = 15
max-positional-arguments = 5

[tool.pylint.variables]
ignored-argument-names = "_|arg|args|kwargs|view_func|view_args|view_kwargs|info|request|context|metadata|serializer|root|queryset|owner|staff_tree|ft_type|ft_settings"

[tool.pylint.typecheck]
generated-members = [".*pb2.*"]

[tool.bandit]
exclude_dirs = ["./tests/*", "./resources/*", "./.git/*", "./_dev_resources/*", "./.venv/*"]