-- vim.api.nvim_create_user_command(
--     'Upper',
--     function(opts)
--         local functions = require("config.functions")

--         require("telescope.builtin").find_files({search_dirs={"hooks"}})
--         -- print(functions.normalize_path(vim.fn.getcwd() .. '/' .. opts.args .. '.workspace'))
--         -- vim.g.homebrew.file_ignore_patterns = {".py"}
--         -- local values = {}
--         -- for _, value in ipairs(config.values) do
--         --     table.insert(values, value)
--         -- end
--         -- print(1, table.concat(values, ", "))
--     end,
--     {}
--     -- { nargs = 1 }
-- )